kind: pipeline
name: ElectroPerf Drone

steps:
 - name: compile
   image: archlinux:base-devel
   environment:
     ZIP_RELEASE:
       from_secret: ZIP_RELEASE
     TOKEN:
       from_secret: BOT_API_KEY
     CHATID:
       from_secret: CHAT_ID
     ZIPNAME:
       from_secret: ZIPNAME
   commands:
      - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
      - pacman -Sy && pacman -S git bc inetutils python2 zip wget cpio jdk-openjdk tzdata --noconfirm
      - ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
      - bash builder.sh
