name: ElectroPerf Kernel
env:
      TOKEN: ${{ secrets.BOT_API_KEY }}
      CHATID: ${{ secrets.CHAT_ID }}
on:
  workflow_dispatch:
  push: {branches: ["TP"]}
jobs:
  electroperf-kernel:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
    - name: Upgrade Environment
      run: pacman -Syu --noconfirm --needed git bc inetutils zip libxml2 tzdata python3 jre-openjdk jdk-openjdk flex bison libc++ python-pip
    - name: Setup Time Zone
      run: ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && date
    - name: Proceed With Compilation
      run: bash builder.sh
      
